# Site wide configuration

title: life long learner
locale: en_US
description: Chandan Rai (crowchirp)
logo: site-logo.png
search: true
#url: http://chandanrai.com
#url: http://localhost:4000
name: chandanrai.com
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..4
  enable_coderay: false
  coderay_wrap: div
  coderay_line_numbers: inline


mathjax: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Chandan Rai
  avatar: bio-photo.jpg
  email: crowchirp@gmail.com
  disqus-shortname: crowchirp
  twitter: crowchirp
  facebook: #crowchirp
  github: crowchirp
  stackexchange: http://stackoverflow.com/users/1530987/crowchirp
  linkedin: crowchirp
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-97049734-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
